export default {
  FETCH: 'FETCH',
  CANCEL_FETCH: 'CANCEL_FETCH',
  SET_SYMBOL: 'SET_SYMBOL',
  SET_LATEST_PRICE: 'SET_LATEST_PRICE',
  SET_CHART_DATA: 'SET_CHART_DATA',
  SET_COMPANY: 'SET_COMPANY',
  SET_CURRENT_DATA: 'SET_CURRENT_DATA',
  ADD_DATA: 'ADD_DATA',
  REMOVE_DATA: 'REMOVE_DATA',

};